version: "3.9"

services:
  backend:
    build: ./
    container_name: hinge-analyser-service
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres

  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db-postgres:/var/lib/postgresql/data

volumes:
  db-postgres:
    driver: local